const mongoose=require('mongoose');
const ProductSchema=mongoose.Schema({
    product_name:{
        type:String,
        required:true
    },
    price:{
        type:String,
        required:true
    },
    discount:{
        type:String,
        required:true
    },
    discount_price:{
        type:String,
        required:true
    },
    short_desc:{
        type:String,
        required:true
    },
    long_desc:{
        type:String,
        required:true
    },
    vendor_id:{
        type:mongoose.Schema.Types.ObjectId,
            required:true,
            ref:"users"
    },
    category_id:{
        type:mongoose.Schema.Types.ObjectId,
            required:true,
            ref:"categories"
    },
    video_link:{
        type:String,
        required:true
    },
    fssai:{
        type:String,
        required:true
    },
    product_img:{
        type:String,
        required:true
    },
    stock:{
        type:String,
        required:true
    },
    quantity:{
        type:String,
        required:true
    }
    
})
module.exports=mongoose.model('products',ProductSchema)